#project tree structure
LDIR = lib
SDIR = src
ODIR = obj
BDIR = bin
DDIR = dep

#Compiler flag variables
INC        = $(SDIR) #/usr/local/boost_1_69_0/ # <- Include path to left for using boost header files
INC_PARAMS = $(foreach d, $(INC), -I$d)
DEPFLAGS   = -MT $@ -MMD -MP -MF $(DDIR)/$*.Td
CPPFLAGS   = -std=c++11 -g
LINKFLAGS  = 

#The full command for compilation
CPPC       = g++ $(CPPFLAGS) $(INC_PARAMS) $(DEPFLAGS)
CPPL       = g++ $(CPPFLAGS)
POSTCPPC   = @mv -f $(DDIR)/$*.Td $(DDIR)/$*.d && touch $@

#List all main cpp files
SRCS   = $(patsubst $(SDIR)/%.cpp,%.cpp, $(wildcard $(SDIR)/*\-*.cpp)) 
_BINS  = $(patsubst %.cpp,$(BDIR)/%,$(SRCS))

#List all other cpp files
_SRCS = $(patsubst $(SDIR)/%.cpp,%.cpp, $(wildcard $(SDIR)/[!\-].cpp))

#Default make target: setup the environment, build the program, build and run tests
.PHONY: all
all: | toolchain $(_BINS)

#Program link step
$(BDIR)/%: $(ODIR)/%.o $(patsubst %.cpp, $(ODIR)/%.o, $(_SRCS))
	$(CPPL) -o $@ $^ $(LINKFLAGS)

#All compilation units in the project
$(ODIR)/%.o: $(SDIR)/%.cpp $(DDIR)/%.d
	$(CPPC) -c -o $@ $<
	$(POSTCPPC)

#Standard build targets
.PHONY: clean
clean:
	rm -rf $(DDIR) $(ODIR) $(BDIR)

.PHONY: toolchain
toolchain: | $(BDIR) $(ODIR) $(DDIR)

$(DDIR):
	@mkdir $(DDIR)

$(ODIR):
	@mkdir $(ODIR)

$(BDIR):
	@mkdir $(BDIR)

#Dependency management
$(DDIR)/%.d: ;
.PRECIOUS: $(DDIR)/%.d

include $(wildcard $(patsubst %,$(DDIR)/%.d,$(basename $(SRCS))))
